-- =============================================
-- Smart Poultry IoT - Supabase Schema
-- =============================================

-- Create Readings Table (Temperature & Humidity)
create table if not exists public.readings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  temperature numeric,
  humidity numeric,
  device_id text
);

-- Create Relays Table (Manual Control)
create table if not exists public.relays (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  is_on boolean default false,
  type text, -- 'FEEDER', 'CLEANER', etc.
  direction text default 'FORWARD', -- 'FORWARD' or 'BACKWARD'
  device_id text
);

-- Create Logs Table (Activity Logs)
create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  message text,
  type text default 'INFO'
);

-- Create Sensor Status Table (NEW - For Limit Switch & Other Sensors)
create table if not exists public.sensor_status (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  device_id text,
  sensor_name text,
  is_triggered boolean default false,
  motors_running boolean default false
);

-- Enable Realtime for all tables
alter publication supabase_realtime add table public.readings;
alter publication supabase_realtime add table public.relays;
alter publication supabase_realtime add table public.logs;
alter publication supabase_realtime add table public.sensor_status;

-- Insert Default Relays
insert into public.relays (name, type, device_id) values 
('Auger Feeder', 'FEEDER', 'esp32_feeder'),
('Waste Conveyor', 'CLEANER', 'esp32_feeder')
on conflict do nothing;
