-- =============================================
-- Smart Poultry IoT - Schedules Table
-- Supports fixed-time and interval scheduling
-- =============================================

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  relay_type text not null,
  schedule_mode text default 'fixed',
  schedule_time time,
  interval_minutes int,
  direction text default 'FORWARD',
  duration_seconds int default 30,
  is_active boolean default true,
  last_triggered_at timestamp with time zone,
  label text
);

-- Enable Realtime
alter publication supabase_realtime add table public.schedules;

-- Enable RLS
alter table public.schedules enable row level security;

-- Allow all operations for anon (same pattern as existing tables)
create policy "Allow all for anon" on public.schedules
  for all using (true) with check (true);
