-- Create Readings Table
create table public.readings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  temperature numeric,
  humidity numeric,
  device_id text
);

-- Create Relays Table
create table public.relays (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  is_on boolean default false,
  type text, -- 'FEEDER', 'CLEANER', etc.
  device_id text
);

-- Create Logs Table
create table public.logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  message text,
  type text default 'INFO'
);

-- Enable Realtime
alter publication supabase_realtime add table public.readings;
alter publication supabase_realtime add table public.relays;
alter publication supabase_realtime add table public.logs;

-- Insert Default Relays
insert into public.relays (name, type, device_id) values 
('Auger Feeder', 'FEEDER', 'esp32_01'),
('Waste Conveyor', 'CLEANER', 'esp32_01');
