-- =============================================
-- JALANKAN SQL INI DI SUPABASE SQL EDITOR
-- https://supabase.com/dashboard → SQL Editor
-- =============================================

-- 1. Buat tabel sensor_status (untuk status online/offline)
CREATE TABLE IF NOT EXISTS public.sensor_status (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  device_id text,
  sensor_name text,
  is_triggered boolean default false,
  motors_running boolean default false
);

-- 2. Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.sensor_status;

-- 3. Tambah kolom direction ke relays (jika belum ada)
ALTER TABLE public.relays 
ADD COLUMN IF NOT EXISTS direction text DEFAULT 'FORWARD';

-- 4. Set RLS policy agar ESP32 bisa INSERT
ALTER TABLE public.sensor_status ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous insert" ON public.sensor_status
FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Allow anonymous select" ON public.sensor_status
FOR SELECT TO anon USING (true);
